### ISSUE TITLE
Two pipes with gulpif and waiting for them to finish

### ISSUE THREAD

**Issue by TCB13** [OverZealous/lazypipe#27]
Hello, first of all, thanks for the great project. I've been using it for some time now in order to take a stream and send all `js` files to a pipe and `css` file to another. Like this:

```
gulp.task("optimize-css-js", function(){
      // Other unrelated code //
      return gulp.src(cssjs)
		.pipe(gulpif("*.css", cssPipe())) // Process CSS
		.pipe(gulpif("*.js", jsPipe())); // Process JS
});

var jsPipe = lazypipe()
	.pipe(concat, conf.minified.js)
	.pipe(uglify)
	.pipe(gulp.dest, path.join(conf.distFolder, conf.resourcesDir));

var cssPipe = lazypipe()
	.pipe(cleanCSS, {
		//...
	.pipe(gulp.dest, path.join(conf.distFolder, conf.resourcesDir));
```

Since I included `return` on the task I was expecting the task to only finish *after* both pipes finished their operations, however this doesn't seem to be the case. Due to some reason the task finishes before all files in both pipes are written to the disk... How can I fix this?

Thank you!

**Comment by OverZealous** [comment]
I'm not sure. If you run the pipes separately, does gulp wait as expected? Also, I assume that's pasted out-of-order, since you need to create the lazypipes before you use them.

I've not used lazypipe in that scenario, but there's no reason it shouldn't work. It's a fairly simple functional wrapper around stream-combiner, so I don't think it should prevent the streams from finishing.

I use lazypipe all over in our massive build scripts, and we use them in a lot of ways, but I don't generally like combining different resources that way (I prefer to have dedicated end-to-end streams for each type of file).

**Comment by OverZealous** [comment]
If you can, try to reduce it to a simpler case to see if you can reproduce it with minimal code.

Looking at it some more, I'm not really sure why you're doing what you are doing, anyway, since having two separate Gulp tasks, one for each file type, would be more efficient and easier to manage. The fact that you are outputting them within the gulp-if branching logic seems like a code smell to me.

If you had tasks `optimize-css` and `optimize-js`, then you could even keep your current task, just do this:

```js
gulp.task("optimize-css-js", ["optimize-css", "optimize-js"]);
```

Now those two tasks can run in parallel.

**Comment by TCB13** [comment]
@OverZealous you're right. This was kind of a mess, so after a while I removed the `gulp.dest()` call from the "lazy pipes" and added it to the main stream:
```
gulp.task("optimize-css-js", function(){
      // Other unrelated code //
    return gulp.src(cssjs)
		.pipe(gulpif("*.css", cssPipe())) // Process CSS
		.pipe(gulpif("*.js", jsPipe())) // Process JS
		.pipe(gulp.dest(path.join(conf.distFolder, conf.resourcesDir)));
});

 var jsPipe = lazypipe()
	.pipe(concat, conf.minified.js)
	.pipe(uglify);

var cssPipe = lazypipe()
	.pipe(cleanCSS, {
		//...;
```
There was no point in writing in each pipe because after calling both pipes and adding `gulp-debug` to the stream it showed that only the minified `css` and `js` files were on the pipe. At this stage the task was only finishing *after* all files were written.

I decided to simply this more / follow your advice and ended splitting this into two. In this case I no longer need `gulp-if`.

Thanks for the honest feedback!
